---
repos:
  - hooks:
      - args: [--safe, --quiet]
        files: ^((pyisy|custom_components)/.+)?[^/]+\.py$
        id: black
    repo: https://github.com/psf/black
    rev: 19.10b0
  - hooks:
      - args: ['--ignore-words-list=pyisy,hass,isy,nid,dof,dfof,don,dfon',
               '--skip="./.*,*.json"', --quiet-level=2]
        exclude_types: [json]
        id: codespell
    repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
  - hooks:
      - additional_dependencies: [flake8-docstrings==1.5.0, pydocstyle==5.0.2]
        files: ^(pyisy|custom_components)/.+\.py$
        id: flake8
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
  - hooks:
      - {id: isort}
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
  - hooks:
      - {id: check-json}
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
